[package]
name = "worldseed"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.17"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
crc32fast = "1.4"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
